apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis-slave
  namespace: mitnotes
  labels:
    name: redis-slave
spec:
  replicas: 2
  template:
    metadata:
      name: redis-slave
      namespace: mitnotes
      labels:
        name: redis-slave
    spec:
      containers:
        - name: "slave"
          image: "sadathossain/redis-slave:1.0.0"
          resources:
            limits:
              cpu: 100m
            requests:
              cpu: 100m
          ports:
            - containerPort: 6379
              protocol: "TCP"
